server:
  port: 8082
  context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/health-care-centre?useSSL=false&autoReconnect=true&failOverReadOnly=false&characterEncoding=UTF-8
    username: root
    password: Aaa951202_
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
