server:
  port: 8082
  context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/health_care_centre?useSSL=false&serverTimezone=UTC
    username: root
    password: 951202
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true